version: "3"
services:
  postgres:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=bookmark
    networks:
      - app
    ports:
      - "5433:5432"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - app

  api:
    build:
      context: .
      dockerfile: ./infra/dev/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
      - DB_SOURCE=postgresql://root:secret@postgres:5432/bookmark?sslmode=disable
      - DB_DRIVER=postgres
      - MIGRATION_URL=file://db/migration
      - SERVER_ADDRESS=0.0.0.0:8080
      - TOKEN_SECRET_KEY=12345678901234567890123456789012
      - ACCESS_TOKEN_DURATION=15m
      - REFRESH_TOKEN_DURATION=24h
      - MAIL_HOSTNAME=mailcatcher
      - MAIL_PORT=1025
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - FRONT_URL=http://localhost:3000
    depends_on:
      - postgres
      - mailcatcher
    networks:
      - app
    volumes:
      - .:/go/src/app
    command:
      - "/bin/sh"
      - "-c"
      - "cd /go/src/app && ./wait-for-it.sh postgres:5432 -- air -c .air.toml"

networks:
  app:
    driver: bridge
    external: true
