version: "3.9"
services:
  postgres:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=bookmark
    networks:
      - app
    ports:
      - "5433:5432"

  api:
    build:
      context: .
      dockerfile: ./infra/dev/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/bookmark?sslmode=disable
      - ENV=dev
      - DB_DRIVER=postgres
      - MIGRATION_URL=file://db/migration
      - SERVER_ADDRESS=0.0.0.0:8080
      - TOKEN_SECRET_KEY=12345678901234567890123456789012
      - ACCESS_TOKEN_DURATION=15m
      - REFRESH_TOKEN_DURATION=24h
    depends_on:
      - postgres
    networks:
      - app

networks:
  app:
    driver: bridge
    external: true
