// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Note struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type NoteWeb struct {
	NoteID uuid.UUID `json:"note_id"`
	WebID  uuid.UUID `json:"web_id"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}

type Web struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	Url          string    `json:"url"`
	Title        string    `json:"title"`
	ThumbnailUrl string    `json:"thumbnail_url"`
	CreatedAt    time.Time `json:"created_at"`
}
