// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateNoteWeb(ctx context.Context, arg CreateNoteWebParams) (NoteWeb, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTemporaryUser(ctx context.Context, arg CreateTemporaryUserParams) (TemporaryUser, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWeb(ctx context.Context, arg CreateWebParams) (Web, error)
	DeleteNote(ctx context.Context, id uuid.UUID) error
	DeleteNoteWeb(ctx context.Context, arg DeleteNoteWebParams) error
	DeleteNoteWebsByNoteId(ctx context.Context, noteID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteWeb(ctx context.Context, id uuid.UUID) error
	GetNote(ctx context.Context, id uuid.UUID) (Note, error)
	GetNoteWeb(ctx context.Context, arg GetNoteWebParams) (NoteWeb, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTemporaryUserByToken(ctx context.Context, token string) (TemporaryUser, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetWeb(ctx context.Context, id uuid.UUID) (Web, error)
	ListNoteWebsByNoteId(ctx context.Context, noteID uuid.UUID) ([]NoteWeb, error)
	ListNotesByUserId(ctx context.Context, arg ListNotesByUserIdParams) ([]Note, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWebByNoteId(ctx context.Context, noteID uuid.UUID) ([]Web, error)
	ListWebByNoteIds(ctx context.Context, ids []uuid.UUID) ([]ListWebByNoteIdsRow, error)
	ListWebsByUserId(ctx context.Context, arg ListWebsByUserIdParams) ([]Web, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
