// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: web.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWeb = `-- name: CreateWeb :one
INSERT INTO webs (
  user_id,
  url,
  title,
  thumbnail_url
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, url, title, thumbnail_url, created_at
`

type CreateWebParams struct {
	UserID       uuid.NullUUID `json:"user_id"`
	Url          string        `json:"url"`
	Title        string        `json:"title"`
	ThumbnailUrl string        `json:"thumbnail_url"`
}

func (q *Queries) CreateWeb(ctx context.Context, arg CreateWebParams) (Web, error) {
	row := q.db.QueryRowContext(ctx, createWeb,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.ThumbnailUrl,
	)
	var i Web
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.ThumbnailUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getWeb = `-- name: GetWeb :one
SELECT id, user_id, url, title, thumbnail_url, created_at FROM webs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWeb(ctx context.Context, id uuid.UUID) (Web, error) {
	row := q.db.QueryRowContext(ctx, getWeb, id)
	var i Web
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.ThumbnailUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listWebsByUserId = `-- name: ListWebsByUserId :many
SELECT id, user_id, url, title, thumbnail_url, created_at FROM webs
WHERE user_id = $1
LIMIT $2
OFFSET $3
`

type ListWebsByUserIdParams struct {
	UserID uuid.NullUUID `json:"user_id"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListWebsByUserId(ctx context.Context, arg ListWebsByUserIdParams) ([]Web, error) {
	rows, err := q.db.QueryContext(ctx, listWebsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Web{}
	for rows.Next() {
		var i Web
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.ThumbnailUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
