// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/inkclip/backend/mail (interfaces: Client)

// Package mockmail is a generated GoMock package.
package mockmail

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mail "github.com/inkclip/backend/mail"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockClient) Send(arg0 mail.SendContent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockClient)(nil).Send), arg0)
}

// VertifyMailContent mocks base method.
func (m *MockClient) VertifyMailContent(arg0, arg1 string) mail.SendContent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VertifyMailContent", arg0, arg1)
	ret0, _ := ret[0].(mail.SendContent)
	return ret0
}

// VertifyMailContent indicates an expected call of VertifyMailContent.
func (mr *MockClientMockRecorder) VertifyMailContent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VertifyMailContent", reflect.TypeOf((*MockClient)(nil).VertifyMailContent), arg0, arg1)
}
